site_name: Koala Framework Dokumentation
theme: slate

pages:
- Documentation: 'index.md'
- Installation (3.8+):
    - Local Development Environment:
                - Php built-in webserver:
                      - 'Overview': 'installation-three-point-eight/local-development-environment/php-builtin-webserver.md'
                      - 'Composer': 'installation-three-point-eight/local-development-environment/php-builtin-webserver/composer.md'
                      - 'NodeJS + NPM': 'installation-three-point-eight/local-development-environment/php-builtin-webserver/nodejs-npm.md'

                - Apache: 'installation-three-point-eight/local-development-environment/apache.md'
                - Virtual Machine: 'installation-three-point-eight/local-development-environment/virtual-machine.md'

    - Deployment to remote Server:
                - 'with resync': 'installation-three-point-eight/deployment-to-remote-server/with-resync.md'
                - 'with FTP': 'installation-three-point-eight/deployment-to-remote-server/with-ftp.md'

    - Setup:
                - 'Overview': 'installation-three-point-eight/setup.md'
                - 'Browser based': 'installation-three-point-eight/setup/browser-based.md'
                - 'From Commandline': 'installation-three-point-eight/setup/from-commandline.md'
    - Ubuntu Example: 'installation-three-point-eight/ubuntu-example.md'

- Kwf(General Features):
    - Config:
                - 'Overview': 'kwf-general-features/config.md'
                - 'Https': 'kwf-general-features/config/https.md'
                - 'PreLogin': 'kwf-general-features/config/prelogin.md'
    - Models:
                - 'Overview': 'kwf-general-features/models.md'
                - 'Setup Database': 'kwf-general-features/models/setup-database.md'
                - 'Basic Usage': 'kwf-general-features/models/basic-usage.md'
                - 'Relations': 'kwf-general-features/models/relations.md'
                - 'Select (query)': 'kwf-general-features/models/select-query.md'
                - 'Expressions': 'kwf-general-features/models/expressions.md'
                - 'Stored Expressions': 'kwf-general-features/models/stored-expressions.md'
                - 'Filters': 'kwf-general-features/models/filters.md'
                - 'Modify Row Behavior': 'kwf-general-features/models/modify-row-behavior.md'
                - 'Row __toString': 'kwf-general-features/models/row-tostring.md'
                - 'Export / Import': 'kwf-general-features/models/export-import.md'
                - 'Deleted Flag': 'kwf-general-features/models/deleted-flag.md'
                - 'Mappings': 'kwf-general-features/models/mappings.md'
                - 'Iterators': 'kwf-general-features/models/iterators.md'
                - 'Updates/Structure Changes': 'kwf-general-features/models/update-structure-changes.md'
    - Controllers:
                - 'Overview': 'kwf-general-features/controllers.md'
                - 'Quick Start': 'kwf-general-features/controllers/quick-start.md'
                - 'Cli Controllers': 'kwf-general-features/controllers/cli-controllers.md'
    - Users:
                - 'Overview': 'kwf-general-features/users.md'
                - 'User Model': 'kwf-general-features/users/user-model.md'
                - 'Config': 'kwf-general-features/users/config.md'
                - 'User Management': 'kwf-general-features/users/user-management.md'
                - 'Auth Methods': 'kwf-general-features/users/auth-methods.md'
                - 'Auth: Google OAuth Login': 'kwf-general-features/users/auth-google-login.md'
    - Acl:
                - 'Overview': 'kwf-general-features/acl.md'
                - 'Quick Start': 'kwf-general-features/acl/quick-start.md'
                - 'Usage in Controllers': 'kwf-general-features/acl/usage-in-controllers.md'
                - 'Backend Menu': 'kwf-general-features/acl/backend-menu.md'
                - 'Backend Login Appearance': 'kwf-general-features/acl/backend-login-appearance.md'
                - 'Backend Menu Order': 'kwf-general-features/acl/backend-menu-order.md'
    - ExtJS Integration:
                - 'Overview': 'kwf-general-features/extjs-integration.md'
                - 'Quick Start': 'kwf-general-features/extjs-integration/quick-start.md'
                - 'Start Controller': 'kwf-general-features/extjs-integration/start-controller.md'
                - 'Set Dashboard in backend': 'kwf-general-features/extjs-integration/set-dashboard-in-backend.md'
    - Ajax / Connection:
                - 'Overview': 'kwf-general-features/ajax-connection.md'
                - 'Keep Alive': 'kwf-general-features/ajax-connection/keep-alive.md'
    - AutoForm & AutoGrid:
                - 'Overview': 'kwf-general-features/autoform-autogrid.md'
                - 'AutoForm': 'kwf-general-features/autoform-autogrid/autoform.md'
                - 'AutoForm: columns': 'kwf-general-features/autoform-autogrid/autoform-columns.md'
                - 'AutoGrid': 'kwf-general-features/autoform-autogrid/autogrid.md'
                - 'AutoGrid: renderer': 'kwf-general-features/autoform-autogrid/autogrid-renderer.md'
                - 'AutoGrid: filter': 'kwf-general-features/autoform-autogrid/autogrid-filter.md'
                - 'AutoGrid: Load an id in backend with get parameter': 'kwf-general-features/autoform-autogrid/autogrid-load.md'
                - 'AutoGrid: editDialog': 'kwf-general-features/autoform-autogrid/autogrid-editdialog.md'
                - 'AutoGrid: grouping': 'kwf-general-features/autoform-autogrid/autogrid-grouping.md'
                - 'Tree+Grid binding': 'kwf-general-features/autoform-autogrid/tree-grid-binding.md'
                - 'Custom form/grid class': 'kwf-general-features/autoform-autogrid/custom-form-grid-class.md'
                - 'Custom styling': 'kwf-general-features/autoform-autogrid/custom-styling.md'
    - Kwf_Form:
                - 'Overview': 'kwf-general-features/kwf-form.md'
                - 'Field_ComboBox & Select': 'kwf-general-features/kwf-form/field-combobox.md'
                - 'Container_FieldSet': 'kwf-general-features/kwf-form/container-fieldset.md'
                - 'Container_Cards': 'kwf-general-features/kwf-form/container-cards.md'
                - 'Container_Columns': 'kwf-general-features/kwf-form/container-columns.md'
                - 'Form Validator': 'kwf-general-features/kwf-form/form-validator.md'
                - 'Form to edit Row': 'kwf-general-features/kwf-form/form-to-edit-row.md'
    - Translation:
                - 'Overview': 'kwf-general-features/translation.md'
                - Parsing (3.9+):
                    - 'Overview': 'kwf-general-features/translation/parsing.md'
                    - 'Web': 'kwf-general-features/translation/parsing/web.md'
                    - 'Package': 'kwf-general-features/translation/parsing/package.md'
                    - 'Framework': 'kwf-general-features/translation/parsing/framework.md'
                - Localization (3.9+):
                    - 'Overview': 'kwf-general-features/translation/localization.md'
                    - 'Web': 'kwf-general-features/translation/localization/web.md'
                    - 'Package': 'kwf-general-features/translation/localization/package.md'
                    - 'Framework': 'kwf-general-features/translation/localization/framework.md'
                - 'Update to 3.9': 'kwf-general-features/translation/update.md'
                - 'Localization (< 3.9)': 'kwf-general-features/translation/localization-under-threepointnine.md'
                - 'Parsing (< 3.9)': 'kwf-general-features/translation/parsing-under-threepointnine.md'
                - 'Create Lingohub Project': 'kwf-general-features/translation/create-lingohub-project.md'
    - Asset Dependencies:
                - 'Overview': 'kwf-general-features/asset-dependencies.md'
                - 'Modernizr': 'kwf-general-features/asset-dependencies/modernizr.md'
    - Media Output:
                - 'Overview': 'kwf-general-features/media-output.md'
                - 'Scale Images': 'kwf-general-features/media-output/scale-images.md'
    - Caching:
                - 'Overview': 'kwf-general-features/caching.md'
                - 'Caches': 'kwf-general-features/caching/caches.md'
                - 'Memcache': 'kwf-general-features/caching/memcache.md'
                - 'Clear Cache': 'kwf-general-features/caching/clear-cache.md'
    - Mails:
                - 'Overview': 'kwf-general-features/mails.md'
                - 'Config': 'kwf-general-features/mails/config.md'
                - 'Kwf_Mail': 'kwf-general-features/mails/kwf-mail.md'
                - 'Kwf_Mail_Template': 'kwf-general-features/mails/kwf-mail-template.md'
                - 'Styling': 'kwf-general-features/mails/styling.md'

    - Process Control: 'kwf-general-features/process-control.md'

    - Debugging Techniques: 'kwf-general-features/debugging-techniques.md'

    - Performance:
                - 'Overview': 'kwf-general-features/performance.md'
                - 'Profiling Controllers': 'kwf-general-features/performance/profiling-controllers.md'

    - DomPDF: 'kwf-general-features/dom-pdf.md'


- Kwc (CMS):
    - Introduction: 'kwc-cms/introduction.md'

    - Component Tree:
                - 'Overview': 'kwc-cms/component-tree.md'
                - 'Standard Structure': 'kwc-cms/component-tree/standard-structure.md'
                - 'Settings': 'kwc-cms/component-tree/settings.md'
                - 'Generators': 'kwc-cms/component-tree/generators.md'
                - 'Navigation': 'kwc-cms/component-tree/navigation.md'
                - 'Component Ids': 'kwc-cms/component-tree/component-ids.md'
                - 'Custom Table Generator': 'kwc-cms/component-tree/custom-table-generator.md'
    - Standard Components:
                - 'Overview': 'kwc-cms/standard-components.md'
                - 'Composite': 'kwc-cms/standard-components/composite.md'
                - 'List': 'kwc-cms/standard-components/list.md'
                - 'Paragraphs': 'kwc-cms/standard-components/paragraphs.md'
                - 'TextImage': 'kwc-cms/standard-components/text-image.md'
                - 'LinkTag': 'kwc-cms/standard-components/link-tag.md'
                - 'Link': 'kwc-cms/standard-components/link.md'
                - 'ImageEnlarge': 'kwc-cms/standard-components/image-enlarge.md'
                - 'Html': 'kwc-cms/standard-components/html.md'
                - 'Space': 'kwc-cms/standard-components/space.md'
    - Customize Components:
                - 'Overview': 'kwc-cms/customize-components.md'
                - 'Inherit Component': 'kwc-cms/customize-components/inherit-component.md'
                - 'Component Settings': 'kwc-cms/customize-components/component-settings.md'
                - 'Component Name': 'kwc-cms/customize-components/component-name.md'
                - 'Child Components': 'kwc-cms/customize-components/child-components.md'
                - 'Styling - Css': 'kwc-cms/customize-components/styling-css.md'
                - 'Content - Template': 'kwc-cms/customize-components/content-template.md'
                - 'View Helpers': 'kwc-cms/customize-components/view-helpers.md'
                - 'Behavior - Php': 'kwc-cms/customize-components/behavior-php.md'
                - 'Behavior - JavaScript': 'kwc-cms/customize-components/behavior-javascript.md'
                - 'Behavior - JavaScript + Ajax': 'kwc-cms/customize-components/behavior-javascript-ajax.md'
                - 'Advanced: Backend Menu Item': 'kwc-cms/customize-components/advanced-backend-menu-item.md'
                - 'Add count to specific menu pages': 'kwc-cms/customize-components/add-count.md'
                - 'Dynamic Contents': 'kwc-cms/customize-components/dynamic-contents.md'
                - 'Plugins': 'kwc-cms/customize-components/plugins.md'
                - 'Component Flags': 'kwc-cms/customize-components/component-flags.md'
                - 'Generator Flags': 'kwc-cms/customize-components/generator-flags.md'
                - 'BEM': 'kwc-cms/customize-components/bem.md'
                - 'Rules': 'kwc-cms/customize-components/rules.md'
    - Customize Master:
                - 'Overview': 'kwc-cms/customize-master.md'
                - 'Styling': 'kwc-cms/customize-master/styling.md'
                - 'Box': 'kwc-cms/customize-master/box.md'
                - 'Remove Box': 'kwc-cms/customize-master/remove-box.md'
                - 'MultiBox': 'kwc-cms/customize-master/multi-box.md'
                - 'Add additional Master': 'kwc-cms/customize-master/add-additional-master.md'
                - 'Reset Master for a specific page in web': 'kwc-cms/customize-master/reset-master.md'
    - Susy 2 Grid Styling:
                - 'Overview': 'kwc-cms/susy-two-grid-styling.md'
                - 'Dependencies': 'kwc-cms/susy-two-grid-styling/dependencies.md'
                - 'Master Layout': 'kwc-cms/susy-two-grid-styling/master-layout.md'
                - 'Master-Styling': 'kwc-cms/susy-two-grid-styling/master-styling.md'
                - 'Component Styling: layout context': 'kwc-cms/susy-two-grid-styling/cs-layout-context.md'
                - 'Component Styling: full content width': 'kwc-cms/susy-two-grid-styling/cs-full-content-width.md'
                - 'Component Styling: multiple contexts': 'kwc-cms/susy-two-grid-styling/cs-multiple-contexts.md'
                - 'Component Styling: child contexts': 'kwc-cms/susy-two-grid-styling/cs-child-contexts.md'
                - 'Sass Helper': 'kwc-cms/susy-two-grid-styling/sass-helper.md'
    - Menus:
                - 'Overview': 'kwc-cms/menus.md'
                - 'Create a Menu (and Submenu)': 'kwc-cms/menus/create-menu.md'
                - 'Breadcrumbs': 'kwc-cms/menus/breadcrumbs.md'
                - 'EditableItems': 'kwc-cms/menus/editable-items.md'
    - Directories:
                - 'Overview': 'kwc-cms/directories.md'
                - 'Basic Structure': 'kwc-cms/directories/basic-structure.md'
                - 'Events Components': 'kwc-cms/directories/events-component.md'
                - 'Simple Example': 'kwc-cms/directories/simple-example.md'
                - 'Categories': 'kwc-cms/directories/categories.md'
    - Kwc_Mail_Component:
                - 'Overview': 'kwc-cms/kwc-mail-component.md'
                - 'Structure': 'kwc-cms/kwc-mail-component/structure.md'
                - 'Configuration': 'kwc-cms/kwc-mail-component/configuration.md'
                - 'Styling': 'kwc-cms/kwc-mail-component/styling.md'
                - 'Placeholders': 'kwc-cms/kwc-mail-component/placeholders.md'
                - 'Redirect': 'kwc-cms/kwc-mail-component/redirect.md'
                - 'Kwc_Mail_Editable_Component': 'kwc-cms/kwc-mail-component/kwc-mail-editable-component.md'
    - Newsletter:
                - 'Overview': 'kwc-cms/newsletter.md'
                - 'Quick Start': 'kwc-cms/newsletter/quick-start.md'
                - 'Structure': 'kwc-cms/newsletter/structure.md'
                - 'Subscribe': 'kwc-cms/newsletter/subscribe.md'
                - 'Sending': 'kwc-cms/newsletter/sending.md'
                - 'Categories': 'kwc-cms/newsletter/categories.md'
                - 'Recipients': 'kwc-cms/newsletter/recipients.md'
                - 'Create Custom Components': 'kwc-cms/newsletter/create-custom-components.md'
    - Forms:
                - 'Wizard Component': 'kwc-cms/forms/wizard-component.md'

    - Benchmark Box: 'kwc-cms/benchmark-box.md'

    - JavaScript Fx Helpers:
                - 'Overview': 'kwc-cms/js-fx-helpers.md'
                - 'kwfSwitchHoverFade (dropdown)': 'kwc-cms/js-fx-helpers/kwf-switch-hover-fade.md'
    - Events:
                - 'Overview': 'kwc-cms/events.md'
                - 'Fire Events': 'kwc-cms/events/fire-events.md'
                - 'Koala Events': 'kwc-cms/events/koala-events.md'

    - Frontend Events (JS): 'kwc-cms/frontend-events.md'

    - CC Components: 'kwc-cms/cc-components.md'

    - Fulltext Search:
                - 'Overview': 'kwc-cms/fulltext-search.md'
                - 'Quick Start': 'kwc-cms/fulltext-search/quick-start.md'
                - 'Solr backend': 'kwc-cms/fulltext-search/solr-backend.md'
                - 'Customize Content': 'kwc-cms/fulltext-search/customize-content.md'
    - Styling (general):
                - 'Z-Indices': 'kwc-cms/styling-general.md'
    - Subroot:
                - 'Overview': 'kwc-cms/subroot.md'
                - 'Examples': 'kwc-cms/subroot/examples.md'
                - 'Navigation with Subroots': 'kwc-cms/subroot/navigation-with-subroots.md'
                - 'Base Properties': 'kwc-cms/subroot/base-properties.md'
    - Statistics:
                - 'Overview': 'kwc-cms/statistics.md'
                - 'Google Analytics': 'kwc-cms/statistics/google-analytics.md'
                - 'Piwik': 'kwc-cms/statistics/piwik.md'

    - Maintenance Jobs: 'kwc-cms/maintenance-jobs.md'

    - Domain configurations: 'kwc-cms/domain-configurations.md'

- Sass:
    - Introduction: 'sass/introduction.md'
    - Background Image Dpr2: 'sass/background-image.md'
    - Mobile Breakpoint: 'sass/mobile-breakpoint.md'
    - Form Styling Mixin: 'sass/form-styling-mixin.md'
    - Debugging: 'sass/debugging.md'

- Changelog: 'changelog/changelog.md'

- Development:
    - Overview: 'development/development.md'
    - Coding Standards: 'development/coding-standards.md'
    - Unit Tests: 'development/unit-tests.md'
    - Windows Development: 'development/windows-development.md'
    - Intern:
              - 'Clone existing Web': 'development/intern/clone-existing-web.md'
              - 'Create new Web': 'development/intern/create-new-web.md'
              - 'vps commands': 'development/intern/vps-commands.md'
              - 'Import / Export Data': 'development/intern/import-export-data.md'
              - 'Push changes to Production': 'development/intern/push-changes-to-production.md'
              - 'cherry pick kwf change > 3.8': 'development/intern/cherry-pick-kwf-changes.md'
              - 'Git Basics': 'development/intern/git-basics.md'
              - 'Git Advanced': 'development/intern/git-advanced.md'
              - 'Initial Setup Online': 'development/intern/initial-setup-online.md'
              - 'Initial Tag / Freeze Web': 'development/intern/initial-tag-freeze-web.md'
              - 'Rename Web': 'development/intern/rename-web.md'
              - 'Copy Web': 'development/intern/copy-web.md'
              - 'Private Fonts Repository': 'development/intern/private-fonts-repository.md'
              - 'Various Console-Snippets': 'development/intern/various-console-snippets.md'
              - 'Various Snippets': 'development/intern/various-snippets.md'
              - 'Various CSS Snippets': 'development/intern/various-css-snippets.md'
              - 'Install XHGui': 'development/intern/install-xh-gui.md'
              - 'Bower Link': 'development/intern/bower-link.md'
              - 'Mail Styling': 'development/intern/mail-styling.md'
              - 'Mail Testing': 'development/intern/mail-testing.md'
              - Packages:
                    - 'poi-shop': 'development/intern/packages/poi-shop.md'






